### ISSUE TITLE
Suggestion: Move to JS modules for better portability

### ISSUE THREAD

**Issue by Oliver-makes-code** [greys-tools/pkapi.js#3]
Using JS modules would allow better portability between other runtimes, like [Deno](https://deno.land).

**Comment by greysdawn** [comment]
we were actually planning to do this originally, but ended up scrapping it because we couldn't find many good resources for exporting both mjs code and cjs code. might look into that to try it again, though we're also thinking about rewriting this module in typescript which might make that easier

**Comment by greysdawn** [comment]
as of the [latest release](https://github.com/greys-tools/pkapi.js/releases/tag/v4.0.1), the code is now using esmodules :3
