### ISSUE TITLE
TypeError on getFronters() when used on a system without any registered switches

### ISSUE THREAD

**Issue by z0w13** [greys-tools/pkapi.js#6]
The PluralKit API [returns a `204 No Content`](https://github.com/PluralKit/PluralKit/blob/main/PluralKit.API/Controllers/v2/SwitchControllerV2.cs#L65-L67) when a system does not have any registered switches.

This results in a `TypeError: can't access property "map", resp.data.members is undefined` when calling `pk.getFronters()` on said systems

**Comment by greysdawn** [comment]
Should be fixed in the latest release! Thanks for the bug report o7
