### ISSUE TITLE
member.last_message_timestamp can be null, but it gets parsed as a date anyway

### ISSUE THREAD

**Issue by z0w13** [greys-tools/pkapi.js#7]
When a system member has never sent a message their `last_message_timestamp` will be null, but this still gets parsed into a Date object with a unix timestamp of 0

It would be a breaking change for pkapi.js to also set this to null, but it would correctly reflect the API response.

**Comment by greysdawn** [comment]
thanks for the catch! went ahead and fixed that. also caught the issue with `last_latch_timestamp`, as that should be nullable as well ^^

latest version should have the fixes o7
